version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prd
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    env_file:
      - ./server/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  web-root:
    driver: local
